version: '3.1'
services:
    server:
        image: registry.fit2cloud.org/demo-app:latest
        labels:
            - traefik.enable=true
            - traefik.http.routers.demo-app.rule=Host(`demo.${DOMAIN}`)
            - traefik.http.routers.demo-app.tls.certresolver=le
            - com.centurylinklabs.watchtower.enable=true
networks:
    default:
        external: true
        name: traefik